/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'prakash' at '8/5/17 8:25 PM' with Gradle 2.9
 *
 * @author prakash, @date 8/5/17 8:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
